/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class MiniSearch {
  constructor(options: any)
  /**
   * Deserializes an index serialized with `toJSON`/`JSON.stringify`. The
   * same options used when serializing must be provided.
   */
  static loadJson(json: string, options: any): MiniSearch
  add(document: any): void
  addAll(documents: Array<any>): void
  remove(document: any): void
  /**
   * Removes the given documents. When called without arguments, removes
   * all documents, resetting the index.
   */
  removeAll(documents?: Array<any> | undefined | null): void
  discard(id: any): void
  discardAll(ids: Array<any>): void
  replace(document: any): void
  /**
   * Cleans up references to discarded documents. Native vacuuming is
   * synchronous and complete; there is no main thread to block.
   */
  vacuum(): void
  has(id: any): boolean
  getStoredFields(id: any): any | null
  /**
   * Searches the index. Takes a query string or a combination query
   * object with a `queries` array, and returns scored results sorted by
   * descending score. Search mutates the index only to clean up stale
   * references to discarded documents, exactly like the original.
   */
  search(query: any, options?: any | undefined | null): Array<any>
  /**
   * Same as `search`, returning the results as a JSON string. Crossing
   * the native boundary once and parsing with `JSON.parse` is much faster
   * than materializing result objects through the bindings.
   */
  searchJson(query: any, options?: any | undefined | null): string
  /**
   * Returns results for all documents, equivalent to searching with the
   * `MiniSearch.wildcard` symbol in the original API.
   */
  wildcardSearch(options?: any | undefined | null): Array<any>
  autoSuggest(query: string, options?: any | undefined | null): Array<any>
  get documentCount(): number
  get termCount(): number
  get dirtCount(): number
  get dirtFactor(): number
  toJson(): any
}
