import { describe, expect, test } from "bun:test";
import JsMiniSearch from "minisearch";
// @ts-expect-error generated by napi build
import { MiniSearch } from "../index.js";

type Doc = Record<string, unknown> & { id: number };

const documents: Doc[] = [
  { id: 1, title: "Moby Dick", text: "Call me Ishmael. Some years ago I sailed the seas", category: "fiction" },
  { id: 2, title: "Zen and the Art of Motorcycle Maintenance", text: "I can see by my watch that it is time to ride the motorcycle", category: "fiction" },
  { id: 3, title: "Neuromancer", text: "The sky above the port was the color of television", category: "fiction" },
  { id: 4, title: "Zen and the Art of Archery", text: "At first sight it must seem that the art of archery is zen", category: "non-fiction" },
  { id: 5, title: "Gödel, Escher, Bach", text: "An eternal golden braid of art and logic", category: "non-fiction" },
  { id: 6, title: "The Art of War", text: "All warfare is based on deception and art", category: "non-fiction" },
  { id: 7, title: "Zen Mind, Beginner's Mind", text: "In the beginner's mind there are many possibilities", category: "non-fiction" },
  { id: 8, title: "Motorcycle Diaries", text: "A journey across South America on an old motorcycle", category: "biography" },
];

const options = {
  fields: ["title", "text"],
  storeFields: ["title", "category"],
};

function buildBoth() {
  const js = new JsMiniSearch(options);
  js.addAll(documents);
  const rust = new MiniSearch(options);
  rust.addAll(documents);
  return { js, rust };
}

function expectSameResults(jsResults: any[], rustResults: any[]) {
  expect(rustResults.length).toBe(jsResults.length);
  for (let i = 0; i < jsResults.length; i++) {
    const expected = jsResults[i];
    const actual = rustResults[i];
    expect(actual.id).toBe(expected.id);
    expect(actual.score).toBeCloseTo(expected.score, 10);
    expect(actual.terms.toSorted()).toEqual(expected.terms.toSorted());
    expect(actual.queryTerms.toSorted()).toEqual(expected.queryTerms.toSorted());
    expect(actual.match).toEqual(expected.match);
    expect(actual.title).toEqual(expected.title);
    expect(actual.category).toEqual(expected.category);
  }
}

describe("search parity with minisearch", () => {
  test("plain OR search", () => {
    const { js, rust } = buildBoth();
    expectSameResults(js.search("zen art motorcycle"), rust.search("zen art motorcycle"));
  });

  test("single term", () => {
    const { js, rust } = buildBoth();
    expectSameResults(js.search("art"), rust.search("art"));
  });

  test("empty query returns no results", () => {
    const { js, rust } = buildBoth();
    expect(rust.search("")).toEqual([]);
    expect(js.search("")).toEqual([]);
  });

  test("restricted fields", () => {
    const { js, rust } = buildBoth();
    const opts = { fields: ["title"] };
    expectSameResults(js.search("art", opts), rust.search("art", opts));
  });

  test("field boosting", () => {
    const { js, rust } = buildBoth();
    const opts = { boost: { title: 2 } };
    expectSameResults(js.search("zen art", opts), rust.search("zen art", opts));
  });

  test("prefix search", () => {
    const { js, rust } = buildBoth();
    const opts = { prefix: true };
    expectSameResults(js.search("moto", opts), rust.search("moto", opts));
    expectSameResults(js.search("art moto", opts), rust.search("art moto", opts));
  });

  test("fuzzy search", () => {
    const { js, rust } = buildBoth();
    expectSameResults(js.search("ismael", { fuzzy: 0.2 }), rust.search("ismael", { fuzzy: 0.2 }));
    expectSameResults(js.search("nuromancer", { fuzzy: 2 }), rust.search("nuromancer", { fuzzy: 2 }));
    expectSameResults(js.search("zne", { fuzzy: true }), rust.search("zne", { fuzzy: true }));
  });

  test("prefix and fuzzy combined", () => {
    const { js, rust } = buildBoth();
    const opts = { prefix: true, fuzzy: 0.2 };
    expectSameResults(js.search("moto zen", opts), rust.search("moto zen", opts));
  });

  test("combineWith AND", () => {
    const { js, rust } = buildBoth();
    const opts = { combineWith: "AND" };
    expectSameResults(js.search("zen art", opts), rust.search("zen art", opts));
  });

  test("combineWith AND_NOT", () => {
    const { js, rust } = buildBoth();
    const opts = { combineWith: "AND_NOT" };
    expectSameResults(js.search("art zen", opts), rust.search("art zen", opts));
  });

  test("query combination tree", () => {
    const { js, rust } = buildBoth();
    const query = {
      combineWith: "AND",
      queries: ["zen", { combineWith: "OR", queries: ["motorcycle", "archery"] }],
    };
    expectSameResults(js.search(query as any), rust.search(query));
  });

  test("weights and bm25 overrides", () => {
    const { js, rust } = buildBoth();
    const opts = {
      fuzzy: 0.2,
      prefix: true,
      weights: { fuzzy: 0.3, prefix: 0.5 },
      bm25: { k: 1.5, b: 0.5, d: 0.4 },
    };
    expectSameResults(js.search("moto", opts), rust.search("moto", opts));
  });

  test("wildcard search", () => {
    const { js, rust } = buildBoth();
    const jsResults = js.search(JsMiniSearch.wildcard);
    const rustResults = rust.wildcardSearch();
    expectSameResults(jsResults, rustResults);
  });
});

describe("autoSuggest parity", () => {
  test("basic suggestions", () => {
    const { js, rust } = buildBoth();
    const jsSuggestions = js.autoSuggest("zen ar");
    const rustSuggestions = rust.autoSuggest("zen ar");
    expect(rustSuggestions.length).toBe(jsSuggestions.length);
    for (let i = 0; i < jsSuggestions.length; i++) {
      expect(rustSuggestions[i].suggestion).toBe(jsSuggestions[i].suggestion);
      expect(rustSuggestions[i].terms).toEqual(jsSuggestions[i].terms);
      expect(rustSuggestions[i].score).toBeCloseTo(jsSuggestions[i].score, 10);
    }
  });

  test("fuzzy suggestions", () => {
    const { js, rust } = buildBoth();
    const jsSuggestions = js.autoSuggest("neromancer", { fuzzy: 0.2 });
    const rustSuggestions = rust.autoSuggest("neromancer", { fuzzy: 0.2 });
    expect(rustSuggestions.map((s: any) => s.suggestion)).toEqual(
      jsSuggestions.map((s) => s.suggestion),
    );
  });
});

describe("document lifecycle parity", () => {
  test("counts and membership", () => {
    const { js, rust } = buildBoth();
    expect(rust.documentCount).toBe(js.documentCount);
    expect(rust.termCount).toBe(js.termCount);
    expect(rust.has(3)).toBe(true);
    expect(rust.has(99)).toBe(false);
    expect(rust.getStoredFields(4)).toEqual(js.getStoredFields(4) as any);
  });

  test("remove then search", () => {
    const { js, rust } = buildBoth();
    js.remove(documents[1]);
    rust.remove(documents[1]);
    expectSameResults(js.search("motorcycle"), rust.search("motorcycle"));
    expect(rust.termCount).toBe(js.termCount);
  });

  test("discard, search self-healing, and vacuum", () => {
    const { js, rust } = buildBoth();
    js.discard(2);
    rust.discard(2);
    expect(rust.dirtCount).toBe(js.dirtCount);
    expectSameResults(js.search("motorcycle"), rust.search("motorcycle"));
    rust.vacuum();
    expect(rust.dirtCount).toBe(0);
    expectSameResults(js.search("zen"), rust.search("zen"));
  });

  test("replace", () => {
    const { js, rust } = buildBoth();
    const updated = { ...documents[2], title: "Neuromancer Redux" };
    js.replace(updated);
    rust.replace(updated);
    expectSameResults(js.search("redux"), rust.search("redux"));
  });

  test("duplicate and missing IDs raise the same errors", () => {
    const { rust } = buildBoth();
    expect(() => rust.add(documents[0])).toThrow("MiniSearch: duplicate ID 1");
    expect(() => rust.add({ title: "No ID" } as any)).toThrow(
      'MiniSearch: document does not have ID field "id"',
    );
  });
});

describe("serialization parity", () => {
  test("toJSON matches minisearch shape", () => {
    const { js, rust } = buildBoth();
    const jsPlain = JSON.parse(JSON.stringify(js));
    const rustPlain = rust.toJson();
    expect(rustPlain.serializationVersion).toBe(jsPlain.serializationVersion);
    expect(rustPlain.documentCount).toBe(jsPlain.documentCount);
    expect(rustPlain.nextId).toBe(jsPlain.nextId);
    expect(rustPlain.documentIds).toEqual(jsPlain.documentIds);
    expect(rustPlain.fieldIds).toEqual(jsPlain.fieldIds);
    expect(rustPlain.fieldLength).toEqual(jsPlain.fieldLength);
    expect(rustPlain.averageFieldLength).toEqual(jsPlain.averageFieldLength);
    expect(rustPlain.storedFields).toEqual(jsPlain.storedFields);
    const sortByTerm = (a: [string, unknown], b: [string, unknown]) => a[0].localeCompare(b[0]);
    expect(rustPlain.index.toSorted(sortByTerm)).toEqual(jsPlain.index.toSorted(sortByTerm));
  });

  test("ferrosearch loads a minisearch-serialized index", () => {
    const { js } = buildBoth();
    const rust = MiniSearch.loadJson(JSON.stringify(js), options);
    expectSameResults(js.search("zen art motorcycle"), rust.search("zen art motorcycle"));
    expect(rust.documentCount).toBe(js.documentCount);
  });

  test("minisearch loads a ferrosearch-serialized index", () => {
    const { rust } = buildBoth();
    const js = JsMiniSearch.loadJSON(JSON.stringify(rust.toJson()), options);
    expectSameResults(js.search("zen art motorcycle"), rust.search("zen art motorcycle"));
  });
});
